# Generated by Django 2.2.5 on 2021-03-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_score', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('rec', models.BooleanField(blank=True, default=False)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Subject')),
            ],
        ),
    ]
