# Generated by Django 2.2.5 on 2021-03-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rec'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rec',
            new_name='Recommendation',
        ),
    ]
