# Generated by Django 2.2.5 on 2021-04-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210329_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='clipart',
            field=models.ImageField(blank=True, default='', upload_to='media'),
        ),
    ]
