# Generated by Django 2.2.5 on 2021-04-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_subject_clipart'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='f_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
