# Generated by Django 2.2.5 on 2021-04-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_number', models.CharField(max_length=50)),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
