# Generated by Django 2.2.5 on 2021-04-02 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_type', models.CharField(max_length=100)),
                ('personality_des', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='personality_study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.CharField(max_length=100)),
                ('peronality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personality_test.personality')),
            ],
        ),
        migrations.CreateModel(
            name='personality_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('peronality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personality_test.personality')),
            ],
        ),
    ]
