# Generated by Django 2.2.5 on 2021-04-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0002_personality_personality_job_personality_study'),
    ]

    operations = [
        migrations.DeleteModel(
            name='personality_study',
        ),
    ]
