# Generated by Django 2.2.5 on 2021-04-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0004_personality_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=100)),
                ('cluster_des', models.TextField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='personality_study',
            name='peronality',
        ),
        migrations.AlterField(
            model_name='personality',
            name='personality_des',
            field=models.TextField(max_length=10000),
        ),
        migrations.DeleteModel(
            name='personality_job',
        ),
        migrations.DeleteModel(
            name='personality_study',
        ),
    ]
