# Generated by Django 2.2.5 on 2021-04-02 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0005_auto_20210402_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='personality_cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(max_length=100)),
                ('career_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personality_test.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='cluster_major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('career_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personality_test.cluster')),
            ],
        ),
    ]
