# Generated by Django 2.2.5 on 2021-04-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0006_cluster_major_personality_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='personality_des',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='personality',
            name='personality_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
