# Generated by Django 2.2.5 on 2021-04-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0008_auto_20210402_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='personality_des',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
