# Generated by Django 2.2.5 on 2021-04-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0009_auto_20210402_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='per',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
