# Generated by Django 2.2.5 on 2021-04-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0010_personality_per'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personality',
            name='per',
        ),
    ]
