# Generated by Django 2.2.5 on 2021-04-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0011_remove_personality_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality_cluster',
            name='clipart',
            field=models.ImageField(blank=True, default='', upload_to='media'),
        ),
    ]
