# Generated by Django 2.2.5 on 2021-04-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality_test', '0012_personality_cluster_clipart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personality_cluster',
            name='clipart',
        ),
        migrations.AddField(
            model_name='cluster',
            name='clipart',
            field=models.ImageField(blank=True, default='', upload_to='media'),
        ),
    ]
