# Generated by Django 2.2.5 on 2021-02-12 09:28

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_teacher_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='edu_level',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='grad_year',
            field=models.PositiveIntegerField(default=2021, null=True, validators=[django.core.validators.MinValueValidator(1985), accounts.models.max_value_current_year]),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='edu_level',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='grad_year',
            field=models.PositiveIntegerField(default=2021, null=True, validators=[django.core.validators.MinValueValidator(1985), accounts.models.max_value_current_year]),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
