# Generated by Django 2.2.5 on 2021-02-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210212_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='edu_level',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='edu_level',
            field=models.CharField(default='', max_length=100),
        ),
    ]
