# Generated by Django 2.2.5 on 2021-03-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210224_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
