# Generated by Django 2.2.5 on 2021-02-08 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('fees', models.FloatField(max_length=10000000)),
                ('no_of_seats', models.IntegerField()),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Institutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=100)),
                ('founder', models.CharField(default='', max_length=100)),
                ('picture', models.FileField(upload_to='')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('pname', models.CharField(max_length=100)),
                ('sentiment', models.CharField(default='', max_length=1000)),
                ('rating', models.IntegerField(null=True)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sentiment.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sentiment.Institutes'),
        ),
    ]
