# Generated by Django 2.2.5 on 2021-02-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('sentiment', models.CharField(default='', max_length=1000)),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
    ]
