# Generated by Django 2.2.5 on 2021-02-25 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0003_course_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='deg_inst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sentiment.Institutes'),
        ),
    ]
