# Generated by Django 2.2.5 on 2021-02-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0004_feedback_deg_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='deg_level',
            field=models.CharField(choices=[('Bachelor Degree', 'Bachelor Degree'), ('Associate Degree', 'Associate Degree'), ("Master's Degree", "Master's Degree"), ('Doctoral Degree', 'Doctoral Degree')], default='', max_length=20),
        ),
    ]
