# Generated by Django 2.2.5 on 2021-02-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0005_feedback_deg_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='enroll_status',
            field=models.CharField(choices=[('Currently attending', 'Currently attending'), ('Graduated', 'Graduated'), ('No longer attending', 'No longer attending')], default='', max_length=20),
        ),
    ]
