# Generated by Django 2.2.5 on 2021-02-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0007_feedback_grad_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='class_env',
            field=models.CharField(choices=[('Online', 'Online'), ('On Campus', 'On Campus'), ('Hybrid/Both', 'Hybrid/Both')], default='', max_length=20),
        ),
    ]
