# Generated by Django 2.2.5 on 2021-02-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0008_feedback_class_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='class_env',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='deg_level',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='enroll_status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
