# Generated by Django 2.2.5 on 2021-02-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0010_auto_20210225_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='tot_rating',
            field=models.IntegerField(null=True),
        ),
    ]
