# Generated by Django 2.2.5 on 2021-02-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0011_feedback_tot_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='overall_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
