# Generated by Django 2.2.5 on 2021-02-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0012_auto_20210226_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='graph',
            field=models.ImageField(default='media/christ.jpg', upload_to=''),
        ),
    ]
