# Generated by Django 2.2.5 on 2021-02-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0013_course_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='graph',
            field=models.ImageField(blank=True, default='', upload_to='media'),
        ),
    ]
