# Generated by Django 2.2.5 on 2021-03-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0015_institutes_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sentiment',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
