# Generated by Django 2.2.5 on 2021-03-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0016_course_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='neg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='neu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
