# Generated by Django 2.2.5 on 2021-03-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0018_auto_20210314_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='graph',
        ),
    ]
