# Generated by Django 2.2.5 on 2021-03-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0019_remove_course_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sentiment',
        ),
    ]
