# Generated by Django 2.2.5 on 2021-03-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0003_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='career_des',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='discipline',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
