# Generated by Django 2.2.5 on 2021-03-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0005_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='discipline',
        ),
        migrations.DeleteModel(
            name='Career',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
