# Generated by Django 2.2.5 on 2021-03-26 10:04

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0008_auto_20210326_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
