# Generated by Django 2.2.5 on 2021-02-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_degreeinstitution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeinstitution',
            name='is_favorite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
