# Generated by Django 2.2.5 on 2021-03-04 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210221_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DegreeInstitution',
        ),
    ]
