# Generated by Django 2.2.5 on 2021-03-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0005_delete_degreeinstitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=100)),
                ('Degree_Course', models.CharField(max_length=100)),
                ('Institute_name', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=100)),
                ('Total_Fees', models.CharField(max_length=100)),
                ('Ranked', models.CharField(max_length=100)),
                ('is_favorite', models.BooleanField(blank=True, default=False)),
                ('person_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
